### PR TITLE
[DO NOT MERGE] upgrade versioning logic for dependabot

### PR DESCRIPTION
**Pull request by pvdb**
This applies our gemstash-compatible versioning algorithm to the versioning logic original to this forked gem.

Marked as `[DO NOT MERGE]`, as - in its current form - it generates invalid semver strings:

```ruby
$ ruby -Ilib -rmail -e "puts Mail::VERSION::STRING"
2.8.2.edge
$ GEM_PRE_RELEASE=blegga ruby -Ilib -rmail -e "puts Mail::VERSION::STRING"
2.8.2.edge.blegga
$ _
```

the latter is an invalid semver string:

```
$ ruby -r semantic -e 'puts Semantic::Version.new("2.8.2.edge.blegga")'
/Library/Ruby/Gems/2.3.0/gems/semantic-1.6.1/lib/semantic/version.rb:15:in `initialize': 2.8.2.edge.blegga is not a valid SemVer Version (http://semver.org) (ArgumentError)
	from -e:1:in `new'
	from -e:1:in `<main>'
$ _
```

### CODE REVIEW

**Review by lukaso — APPROVED** [review]
This is the current behaviour we have always had, correct?

**Comment by pvdb** [comment]
> This is the current behaviour we have always had, correct?

Ah, that's a good point... which probably means our Jenkins scripts happily accept non-valid semver strings, and - wild guess here - consider `edge.blegga` as the "build" version?  🤔

**Comment by lukaso** [comment]
yep. Ship it and see if we can get rid of the fork?

**Comment by pvdb** [comment]
> yep. Ship it and see if we can get rid of the fork?

I don't think we need to ship it... AFAICT, we no longer use or have a need for this fork:

https://github.com/simplybusiness/chopin/pull/11404

Chopin no longer pulls the `mail` gem from gemstash, but rather from the upstream github repo.

@lesleh - it looks like you did all the heavy lifting here... can you confirm that we can nuke our fork, and remove all traces of the `mail` gem from our gemstash server?

**Comment by pvdb** [comment]
> [...] which probably means our Jenkins scripts happily accept non-valid semver strings, and - wild guess here - consider `edge.blegga` as the "build" version? 🤔

That's indeed what's going on by the looks of it... this is a list of `mail` gem versions on gemstash:

* 2.8.2.edge.gemstashversioninglogic.1
* 2.8.1.removepartslistencoder.2
* 2.8.1.edge
* 2.8.1.edge.removepartslistencoder.1
* 2.8.1.edge.budmovetogemstash.1
* 2.8.0.edge.gemstash.5
* 2.8.0.edge.gemstash.4

_(generated using `gem list --exact --remote --prerelease mail`)_

**Comment by pvdb** [comment]
Closing the PR without merging, as we no longer use this fork, so gonna delete all traces of the forked `mail` gem from our GitHub account as well as our gemstash server. /cc @chrisradford

**Pull request closed without merging**
